[package]
name = "configtpl_py_native"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "configtpl_py_native"
crate-type = ["cdylib"]

[dependencies]
configtpl = "0.1.1"
pyo3 = "0.27.1"
